### ISSUE TITLE
Feature Request: Cobertura output for CI Servers

### ISSUE THREAD

**Issue by alexargo** [appsquickly/frankencover.it#12]
There's a couple script I've found that will do the conversion, but none of them are in groovy. :/. Maybe as an alternative you could leave lcov files hanging around in a "raw" output folder (maybe with some command line switch?) or something along those lines and let people use these other existing scripts? Thoughts? I could probably contribute something along those lines, but I'm not familiar enough with lcov or cobertura to tackle the feature I really want.

**Comment by jasperblues** [comment]
Since none are in Groovy, to get the greatest benefit with a realistic amount of effort, let's remove the cleanup of the lcov output. Instead of 'temp' we can rename the folder to something more descriptive.

**Comment by jasperblues** [comment]
@alexargo Which script did you find the best? I wanted to add some notes on the site about how to do this. . . if it was a Github hosted tool, we could perhaps get the Groovy script to download and execute the python script too.

**Comment by alexargo** [comment]
@jasperblues I am using the script from this repository.

The raw file python script is located at https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py

**Comment by jasperblues** [comment]
@alexargo Thanks for the info. . will add to the website. (Made a fun version of the website yesterday - http://frankencover.it :) )

**Comment by vinnybad** [comment]
@jasperblues @alexargo are these instructions posted anywhere?  I'm trying to access the raw data too for cobertura coverage. Thanks!

**Comment by jasperblues** [comment]
@vinnybad I've added these details to the readme just now.
