### ISSUE TITLE
Failing to run locally

### ISSUE THREAD

**Issue by ryancrosby** [appsquickly/frankencover.it#17]
I think I am missing something right under my nose, but I can't get the report to run from a local copy. When I execute this it works.  
 <code> groovy http://frankencover.it/with -source-dir src/ -required-coverage 85  </code>  

Running this doesn't. 
<code>curl -SSL http://frankencover.it/with > FrankenCliReader && chmod +x FrankenCliReader</code>
<code>./FrankenCliReader -source-dir src/ -required-coverage 85</code>  

I receive the following error:
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
> ..../FrankenCliReader: 15: Invalid duplicate class definition of class FrankenCliReader : The source > ...../FrankenCliReader contains at least two definitions of the class FrankenCliReader.
> One of the classes is an explicit generated class using the class statement, the other is a class generated from the script body based on the file name. Solutions are to change the file name or to change the class name.
>  @ line 15, column 1.
>    class FrankenCliReader
>    ^
>
> 1 error

**Comment by ryancrosby** [comment]
I found the problem with this, https://www.moreofless.co.uk/invalid-duplicate-class-definition-error-groovy/ explains what is going on. The name of the file should not match the name of any classes within the file. I just renamed the script to FrankenReader, and everything is working now.

**Comment by jasperblues** [comment]
Thanks for using frankencover.it :) 

We'll try to get it added to brew/MacPorts as another way to install locally.
