### ISSUE TITLE
location of gcno and gcda

### ISSUE THREAD

**Issue by chouman82** [appsquickly/frankencover.it#18]
so i found the gcno and gcda files under <Project>/build/obj/<Project.build>/<scheme-iphonsimulator>/<target.build>/Objects-normal/i386

so what i ran with 
groovy http://frankencover.it/with -s <Project> -p <path to gcno and gcda files> 

but then i ended up with Coverage data not found... can you shed some light on this?

Caught: java.lang.RuntimeException: 

� Coverage data not found
    � To see how to set build flags, visit http://frankencover.it
    � Exercise your code with tests or otherwise.
    � Run this script again.

java.lang.RuntimeException: 

� Coverage data not found
    � To see how to set build flags, visit http://frankencover.it
    � Exercise your code with tests or otherwise.
    � Run this script again.

	at ReportParser.<init>(with:224)
	at ReportGenerator.printSummary(with:178)
	at ReportGenerator.generate(with:164)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:62)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:13)

**Comment by jasperblues** [comment]
Did you specify the products dir with the full path (not using any unix shorthand) ?

**Comment by jasperblues** [comment]
If still not working run with --debug and post output.

**Comment by chouman82** [comment]
when you say the products dir, you meant the path to the gcno and gcda folder right?  yup have the full path specified.  i'll paste the debug in a bit

**Comment by jasperblues** [comment]
@chouman82 still not working?

**Comment by paulz** [comment]
When I use custom folder for Xcode derived data I had to add -p with that folder name. It is a bit slower as script probably walks the whole tree of derived data, but at least I did not had to specify complete path.

```
groovy http://frankencover.it/with -p "/Volumes/ramdisk/XCodeDerivedData/"  -source-dir MyProjectClasses
```

**Comment by jasperblues** [comment]
OK, glad it works acceptably.
