### ISSUE TITLE
Does not support get coverage while running on device

### ISSUE THREAD

**Issue by cybertk** [appsquickly/frankencover.it#19]
When test is running against device instead of simulator. It's failed to get coverage data.

**Comment by jasperblues** [comment]
I want to help you.

**Comment by jasperblues** [comment]
@cybertk When running on device the coverage data files (*.gcno, *.gcda) will be written out on the device. . . we could get them back off the device again using something like ifuse (http://stackoverflow.com/a/20568346/404201) however this would add too much complexity to the tool. If you wished you could do this manually.
