### ISSUE TITLE
Not possible to enable function coverage

### ISSUE THREAD

**Issue by hybridcattt** [appsquickly/frankencover.it#20]
There is no way to enable function coverage statistic in HTML report.
HTML report can be configured with .lcovrc file, i.e. genhtml_function_coverage = 1, which is enabled by default.
Those settings are being explicitly overridden by genhtml --no-function-coverage --no-branch-coverage.

**Comment by jasperblues** [comment]
Thanks again @hybridcattt

**Comment by hybridcattt** [comment]
Always glad to contribute @jasperblues .
