### ISSUE TITLE
Is it compatible with Swift project?

### ISSUE THREAD

**Issue by lexrus** [appsquickly/frankencover.it#25]
I'd like to generate a coverage report of my Swift projects, but it always return `Coverage data not found` no matter how I built the projects.

**Comment by jasperblues** [comment]
Yes, unfortunately Swift does not support coverage! 

Here's the Radar issue: https://openradar.appspot.com/radar?id=6457429508227072

**Comment by lexrus** [comment]
Okay, thanks.

**Comment by jasperblues** [comment]
I'll update Site with a note about this.

**Comment by NicholasTD07** [comment]
Please update the site about Swift does not support coverage yet. I just tried to get coverage report for a swift project but failed. And after a bit of searching I found this issue. It would be much better that if I've found it earlier in the site. :D

**Comment by jasperblues** [comment]
@NicholasTD07 Done, thanks for your feedback.

**Comment by NicholasTD07** [comment]
@jasperblues WOW, such a swift action! Nice. Thank you.
