### ISSUE TITLE
Code coverage report not picking up all files

### ISSUE THREAD

**Issue by kellyfj** [appsquickly/frankencover.it#27]
ENVIRONMENT
XCode 6.4
Mavericks 10.10.4
$ xcpretty --version
0.1.10
$ lcov --version
lcov: LCOV version 1.11

STEPS
Ran the tests as follows
``xcodebuild test -workspace HacAnalytics.xcworkspace/ -scheme 'HacWrapper' -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4' | xcpretty -c
``

Ran coverage report as follows
```groovy http://frankencover.it/with -source-dir HacWrapper/HacWrapper \
-required-coverage 93```

Report generated
![image](https://cloud.githubusercontent.com/assets/1184211/8851625/b713519e-311e-11e5-9c4e-f7219a4f2c46.png)

But report is missing the main class (HacAnalytics.h and HacAnalytics.m) which is in the source folder
```
$ ls -la HacWrapper/HacWrapper
total 96
drwxr-xr-x  10 kellyfj  wheel   340 Jul 23 09:27 .
drwxr-xr-x   8 kellyfj  wheel   272 Jul 22 08:57 ..
-rw-r--r--   1 kellyfj  wheel  5299 Jul 23 09:26 HacAnalytics.h
-rw-r--r--@  1 kellyfj  wheel  8387 Jul 23 09:27 HacAnalytics.m
-rw-r--r--@  1 kellyfj  wheel   200 Jul  9 12:04 HacSettings.h
-rw-r--r--@  1 kellyfj  wheel   201 Jul  9 12:04 HacSettings.m
-rw-r--r--@  1 kellyfj  wheel   219 Jul  1 09:53 HereSessionId.h
-rw-r--r--@  1 kellyfj  wheel  4176 Jul  1 10:39 HereSessionId.m
-rw-r--r--@  1 kellyfj  wheel   909 Jun 30 14:32 NpsObject.h
-rw-r--r--@  1 kellyfj  wheel  2422 Jun 30 14:33 NpsObject.m
```

and XCode seems to have the files in the right target group

![image](https://cloud.githubusercontent.com/assets/1184211/8851654/ec85c988-311e-11e5-848d-f16c411ad5f1.png)

I tried moving the two files involved into the HacWrapper folder (in XCode) but it didn't make a difference

**Comment by jasperblues** [comment]
Hello @kellyfj !

Can you try running again with --debug option? 

Also, pls try cleaning your ~/Library/Developer/Xcode/DerivedData (or the equivalent AppCode) directory.

**Comment by kellyfj** [comment]
Cleaning the build folder was the trick!

Thanks!

-Frank

**Comment by jasperblues** [comment]
@kellyfj :tada:  :balloon:  This is often the problem, but we thought it would be rude to do that step on behalf of users. I should add it to website/docs though.
