### ISSUE TITLE
Timeout when attempting to install FrankenCover script locally

### ISSUE THREAD

**Issue by gdunnjr** [appsquickly/frankencover.it#29]
I am running the curl command to download the FrankenCover script so that I can run it locally. Here is the curl command I am running (copied from your README.md)

curl -SSL https://frankencover.it/with > FrankenCover && chmod +x FrankenCover

When I run it I receive the following error message:

curl: (7) Failed to connect to frankencover.it port 443: Operation timed out

I have tried on two machines on different networks and both fail.

Thanks!

**Comment by jasperblues** [comment]
Oops. Please use: 

````
curl -SSL http://frankencover.it/with > FrankenCover && chmod +x ./FrankenCover
```
