### ISSUE TITLE
xcode7 issues

### ISSUE THREAD

**Issue by joshrlesch** [appsquickly/frankencover.it#31]
Have you got this to work with xcody 7 yet? I see you removed xcode7 issues from the readme, but am not have to run the frankcover script.

osx: 10.11
xcode 7.01

```
groovy http://frankencover.it/with -source-dir Classes --no-html
Caught: java.lang.RuntimeException:

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException:

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:220)
	at ReportGenerator.printSummary(with:174)
	at ReportGenerator.generate(with:160)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:59)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:15)
```

**Comment by jasperblues** [comment]
Yes, but lcov version 1.12 is required. Available form Brew or MacPorts.

**Comment by jasperblues** [comment]
@joshrlesch Can you confirm all working for you now with lcov 1.12 ?

**Comment by jonsteinmetz** [comment]
> On Oct 20, 2015, at 1:41 AM, Jasper Blues <notifications@github.com> wrote:
> 
> @joshrlesch Can you confirm all working for you now with lcov 1.12 ? 

I can confirm that things are working for me with lcov 1.12.

**Comment by jasperblues** [comment]
:fireworks: thanks @jonsteinmetz

**Comment by gelemias** [comment]
I haven't been able to make it work on Xcode 7.1 and Lcov 1.12 either. ✗ Coverage data not found
Is there something else we need to set up or change to get it running again? Thanks.

**Comment by jasperblues** [comment]
@gelemias You could try and check out the Typhoon project and run the build.sh file there. 

http://github.com/appsquickly/Typhoon

That's an example of a working setup, to verify that your setup is ok.

**Comment by gelemias** [comment]
@jasperblues Thanks!
