### ISSUE TITLE
HTML file not generated

### ISSUE THREAD

**Issue by siddharthan64** [appsquickly/frankencover.it#8]
On running the command 
                *groovy http://frankencover.it/with -source-dir MyProject/Source*

I get the code coverage data generated. However the HTML file seems to be missing inside the build/reports/coverage folder.

**Comment by jasperblues** [comment]
Let's start by checking if this is a problem related to your particular project or a pervasive one: 

* Checkout https://github.com/appsquickly/Typhoon
* Run the build.sh script there. 
* Check for coverage output in the iOS and OSX dirs.

**Comment by siddharthan64** [comment]
Hi Jasper
  groovy http://frankencover.it/with -o /User/sasokan/Downloads doesn't
seem to change the output directory. It throws me the following output on
the terminal

error: Missing required option: s

usage: groovy http://frankencover.it/with -s <sourceDir> <options>

              For instructions on configuring Xcode to output coverage

              data, visit http://frankencover.it

 -a,--appcode                   Search in AppCode's output directory.

                                (default is both Xcode and AppCode's

                                output dirs)

 -d,--debug                     Print debugging output.

 -h,--help                      Help - Usage Information

 -o,--output-dir <arg>          The output directory to write coverage

                                report

 -p,--products-dir <arg>        Use custom directory to search for code

                                coverage files, instead of the IDE default

 -r,--required-coverage <arg>   Required line coverage

 -s,--source-dir <arg>          The source directory to generate coverage

                                for

 -x,--xcode                     Search in Xcode's output directory.

                                (default is both Xcode and AppCode's

                                output dirs)

**Comment by siddharthan64** [comment]
The source directory pointed to didn't have the coverage file. That caused this issue. Instead I just pointed out to the .xcodeproj file. Works fine now.

**Comment by jasperblues** [comment]
Glad it works now, but it's not necessary to point the took at an .xcodeproj file, as source directory will do. As long as tests have been run, and coverage data in the expected place (default is DereicedData) then it will assemble the report for the source files that were found in the specified directory.

**Comment by siddharthan64** [comment]
I guess the issue I had earlier was due to the white space character in the project path. I used the parent folder as the --source--dir instead of the folder with whitespace

**Comment by jasperblues** [comment]
Ah! Makes sense.
